name: 'Terraform GitOps Workflow'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform-cicd-dev:
    name: 'Terraform CICD Dev'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
    steps:
    - name: Install Terraform
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - name: Checkout
      uses: actions/checkout@v3
    - name: Terraform Init
      run: terraform init
    - name: Terraform Format
      run: terraform fmt -check
    # - name: Terraform Plan
    #   run: terraform plan --var-file="vars/dev.tfvars" -input=false
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/"main"' # && github.event_name == 'push'
    #   run: terraform apply --var-file="vars/dev.tfvars" -auto-approve

  terraform-cicd-prod:
    name: 'Terraform CICD Prod'
    if: github.ref == 'refs/heads/"main"'
    needs: terraform-cicd-dev
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        shell: bash
    steps:
    - name: Install Terraform
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - name: Checkout
      uses: actions/checkout@v3
    - name: Terraform Init
      run: terraform init
    # - name: Terraform Plan
    #   run: terraform plan --var-file="vars/prod.tfvars" -input=false
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/"main"' # && github.event_name == 'push'
    #   run: terraform apply --var-file="vars/prod.tfvars" -auto-approve
