name: 'TF Trigger on POST Call'

on:
  repository_dispatch:
    types: [trigger_on_post]

jobs:
  trigger-on-post:
    name: 'Trigger-on-post'
    runs-on: ubuntu-latest
    env: # Sets env variables from our dev environment for plan and apply
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - name: Checkout
      uses: actions/checkout@v3
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan --var-file="vars/dev.tfvars" -input=false
    # - name: Terraform Apply
    #   run: terraform apply --var-file="vars/dev.tfvars" -auto-approve